// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmY4ZiOHh1pQVMaeW65osvM71iYdw0TM',
    appId: '1:478463837582:web:4f8c98d741c7b95a0dd0df',
    messagingSenderId: '478463837582',
    projectId: 'wcas-39ffa',
    authDomain: 'wcas-39ffa.firebaseapp.com',
    storageBucket: 'wcas-39ffa.firebasestorage.app',
    measurementId: 'G-KFQ3WPJ2WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_IL0d-7eL10App0NGUjrEGR1IM2lY2c',
    appId: '1:478463837582:android:bdee1b0c547605080dd0df',
    messagingSenderId: '478463837582',
    projectId: 'wcas-39ffa',
    storageBucket: 'wcas-39ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_S09jvx3kiCwq3Z2qudK-HWH8vfxnTS8',
    appId: '1:478463837582:ios:1bae6b03fd252e390dd0df',
    messagingSenderId: '478463837582',
    projectId: 'wcas-39ffa',
    storageBucket: 'wcas-39ffa.firebasestorage.app',
    iosClientId: '478463837582-8m2cu5jkfkl69bu5s4ngo40htggs70oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.streak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_S09jvx3kiCwq3Z2qudK-HWH8vfxnTS8',
    appId: '1:478463837582:ios:1bae6b03fd252e390dd0df',
    messagingSenderId: '478463837582',
    projectId: 'wcas-39ffa',
    storageBucket: 'wcas-39ffa.firebasestorage.app',
    iosClientId: '478463837582-8m2cu5jkfkl69bu5s4ngo40htggs70oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.streak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvmY4ZiOHh1pQVMaeW65osvM71iYdw0TM',
    appId: '1:478463837582:web:530d4820688da0940dd0df',
    messagingSenderId: '478463837582',
    projectId: 'wcas-39ffa',
    authDomain: 'wcas-39ffa.firebaseapp.com',
    storageBucket: 'wcas-39ffa.firebasestorage.app',
    measurementId: 'G-55S1E2SZBR',
  );

}