/// This file defines the data model for a `Goal`.
/// It includes the Hive type adapter for local storage, serialization logic
/// for Firebase, and utility methods for managing goal properties.

import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../data/util.dart';

part 'goal.g.dart'; // Generated by the Hive generator for type adaptation.

/// Represents a single goal entity in the application.
/// Inherits from `HiveObject` to enable direct use with Hive boxes.
@HiveType(typeId: 0)
class Goal extends HiveObject {
  @HiveField(0)
  String title; // The main title of the goal.

  @HiveField(1)
  String description; // A detailed description of the goal.

  @HiveField(2)
  int streak; // The current streak of consecutive days the goal was updated.

  @HiveField(3)
  DateTime lastUpdate; // The timestamp of the last time the streak was updated.

  @HiveField(4)
  bool
      updated; // A flag indicating if the goal has been updated for the current day.

  @HiveField(5)
  late String id; // A unique identifier for the goal.

  /// Internal constructor for creating a goal instance.
  /// Used by factory constructors to ensure all fields are properly initialized.
  Goal._({
    required this.title,
    required this.description,
    required this.streak,
    required this.lastUpdate,
    required this.updated,
    required this.id,
  });

  /// Public factory for creating a new `Goal`.
  /// It automatically generates a unique ID and sets default values for
  /// streak, lastUpdate, and updated status if they are not provided.
  factory Goal({
    required String title,
    required String description,
    int streak = 0,
    DateTime? lastUpdate,
    bool updated = false,
    String? id,
  }) {
    final newId = id ?? const Uuid().v4(); // Generate a UUID if no id is given.
    // Set a default lastUpdate far in the past to ensure streak logic works correctly on creation.
    final newLastUpdate =
        lastUpdate ?? DateUtil.now().subtract(const Duration(days: 10));

    // Call the private constructor to create the instance.
    return Goal._(
      title: title,
      description: description,
      streak: streak,
      lastUpdate: newLastUpdate,
      updated: updated,
      id: newId,
    );
  }

  /// --- Methods for Firebase Serialization ---

  /// Creates a `Goal` instance from a JSON map (e.g., from Firestore).
  /// It correctly handles the conversion of Firestore's `Timestamp` to a `DateTime`.
  factory Goal.fromJson(Map<String, dynamic> json) {
    return Goal._(
      id: json['id'],
      title: json['title'],
      description: json['description'],
      streak: json['streak'],
      lastUpdate: (json['lastUpdate'] as Timestamp).toDate(),
      updated: json['updated'],
    );
  }

  /// Converts the `Goal` instance into a JSON map for storage in Firestore.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'streak': streak,
      'lastUpdate': lastUpdate,
      'updated': updated,
    };
  }

  /// --- Utility Methods ---

  /// Creates a new `Goal` instance with updated values.
  /// This is useful for immutably updating a goal's state.
  Goal copyWith({
    String? title,
    String? description,
    int? streak,
    DateTime? lastUpdate,
    bool? updated,
    String? id,
  }) {
    return Goal._(
      title: title ?? this.title,
      description: description ?? this.description,
      streak: streak ?? this.streak,
      lastUpdate: lastUpdate ?? this.lastUpdate,
      updated: updated ?? this.updated,
      id: id ?? this.id,
    );
  }

  /// Provides a human-readable string representation of the goal object,
  /// useful for debugging and logging.
  @override
  String toString() {
    return 'Goal{id: $id, title: $title, streak: $streak}';
  }
}
