/// Defines the data model for user-configurable application settings.
/// This class is designed to be stored locally using the Hive database,
/// allowing user preferences to persist across app sessions.

import 'package:hive/hive.dart';
import '../theme/app_theme.dart';

part 'settings.g.dart'; // Generated by the Hive generator for type adaptation.

/// Represents the user's application settings.
///
/// This class is annotated for use with Hive, a lightweight and fast key-value
/// database, to store user preferences persistently on the device.
@HiveType(typeId: 3) // Unique identifier for the Hive type adapter.
class Settings {
  /// The stored index of the selected theme mode (e.g., light, dark, system).
  @HiveField(0) // Unique field index for Hive serialization.
  int themeModeIndex;

  /// The user-defined weight used in the task selection algorithm (1-10).
  @HiveField(1)
  int weight;

  Settings({
    required this.themeModeIndex,
    required this.weight,
  });

  /// A computed property to get the [AppThemeMode] enum from the stored index.
  /// Provides a safe way to access the theme mode, defaulting to light mode
  /// if the stored index is invalid.
  AppThemeMode get themeMode {
    if (themeModeIndex >= 0 && themeModeIndex < AppThemeMode.values.length) {
      return AppThemeMode.values[themeModeIndex];
    }
    return AppThemeMode.light; // Default to light theme as a fallback.
  }

  /// Sets the theme mode by converting the [AppThemeMode] enum to its index.
  set themeMode(AppThemeMode mode) {
    themeModeIndex = mode.index;
  }

  /// A factory constructor to create a `Settings` object with default values.
  /// This is used when initializing settings for the first time.
  factory Settings.create() {
    return Settings(
      themeModeIndex: AppThemeMode.light.index, // Default theme is light.
      weight: 5, // Default weight is neutral (5).
    );
  }

  /// Creates a new `Settings` instance with updated values.
  ///
  /// This method is useful for immutable state updates, allowing for the creation
  /// of a modified copy without changing the original object directly.
  Settings copyWith({
    AppThemeMode? themeMode,
    int? weight,
  }) {
    return Settings(
      themeModeIndex: themeMode?.index ?? themeModeIndex,
      weight: weight ?? this.weight,
    );
  }
}
