/// This file defines the data model for a `Task`.
/// It includes the Hive type adapter for local storage, serialization logic
/// for Firebase, and methods for managing task properties.

import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'task.g.dart'; // Generated by the Hive generator for type adaptation.

/// Represents a single task entity in the application.
/// Inherits from `HiveObject` to enable direct use with Hive boxes.
@HiveType(typeId: 1)
class Task extends HiveObject {
  @HiveField(0)
  String title; // The main title of the task.

  @HiveField(1)
  String description; // A detailed description of the task.

  @HiveField(2)
  List<String> goalIds; // A list of goal IDs this task is associated with.

  @HiveField(3)
  late int
      appearanceCount; // How many times this task can appear before being deleted.

  @HiveField(4)
  late int importance; // A rating of the task's importance (e.g., on a scale).

  @HiveField(5)
  late bool
      display; // Whether the task is currently active or displayed to the user.

  @HiveField(6)
  late String id; // A unique identifier for the task.

  /// Internal constructor for creating a task instance.
  /// Used by factory constructors to ensure all fields are initialized.
  Task._({
    required this.title,
    required this.description,
    required this.goalIds,
    required this.appearanceCount,
    required this.importance,
    required this.display,
    required this.id,
  });

  /// Public factory for creating a new `Task`.
  /// It automatically generates a unique ID if one is not provided and initializes
  /// goalIds to an empty list if null.
  factory Task({
    required String title,
    required String description,
    List<String>? goalIds,
    required int appearanceCount,
    required int importance,
    required bool display,
    String? id,
  }) {
    final newId = id ?? const Uuid().v4(); // Generate a UUID if no id is given.
    final newGoalIds = goalIds ?? []; // Default to an empty list.

    return Task._(
      title: title,
      description: description,
      goalIds: newGoalIds,
      appearanceCount: appearanceCount,
      importance: importance,
      display: display,
      id: newId,
    );
  }

  /// --- Methods for Firebase Serialization ---

  /// Creates a `Task` instance from a JSON map (e.g., from Firestore).
  factory Task.fromJson(Map<String, dynamic> json) {
    return Task._(
      id: json['id'],
      title: json['title'],
      description: json['description'],
      goalIds: List<String>.from(json['goalIds']),
      appearanceCount: json['appearanceCount'],
      importance: json['importance'],
      display: json['display'],
    );
  }

  /// Converts the `Task` instance into a JSON map for storage in Firestore.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'goalIds': goalIds,
      'appearanceCount': appearanceCount,
      'importance': importance,
      'display': display,
    };
  }

  /// --- Business Logic Methods ---

  /// Associates this task with a goal.
  void addGoal(String goalId) {
    if (!goalIds.contains(goalId)) {
      goalIds.add(goalId);
    }
  }

  /// Removes the association of this task from a goal.
  void removeGoal(String goalId) {
    goalIds.remove(goalId);
  }

  /// Creates a new `Task` instance with updated values.
  /// This is useful for immutably updating a task's state.
  Task copyWith({
    String? title,
    String? description,
    List<String>? goalIds,
    int? appearanceCount,
    int? importance,
    bool? display,
    String? id,
  }) {
    return Task._(
      title: title ?? this.title,
      description: description ?? this.description,
      goalIds: goalIds ?? List<String>.from(this.goalIds),
      appearanceCount: appearanceCount ?? this.appearanceCount,
      importance: importance ?? this.importance,
      display: display ?? this.display,
      id: id ?? this.id,
    );
  }

  /// Decrements the appearance count if it is greater than zero.
  /// Returns `true` if the count was successfully decremented.
  bool decrementAppearance() {
    if (appearanceCount > 0) {
      appearanceCount--;
      return true;
    }
    return false;
  }

  /// A getter to determine if the task should be deleted based on its appearance count.
  bool get shouldBeDeleted => appearanceCount <= 0;

  /// Activates the task for display and decrements its appearance count.
  /// Returns `true` if the task was successfully activated.
  bool activate() {
    if (appearanceCount > 0 && !display) {
      display = true;
      appearanceCount--;
      return true;
    }
    return false;
  }
}
